version: "3.1"

services:
  db:
    image: postgres:16.4-bullseye
    container_name: postgres-server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
