apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scheduler-role
  namespace: airflow-example
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - update